version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get update && apt-get install mysql-client -y
  pre_build:
    commands:
      - echo Check AWS, Git, Python version
      - aws --version && git --version && python --version
      - echo Check ENV Variable
      - printenv
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - pwd
      - aws s3 cp s3://rll-stg-environment-bucket/api-event/qa/.env $CODEBUILD_SRC_DIR/qa_test
      - cd qa_test
      - rm -f package-lock.json
      - node --version
      - npm --version
      - npm install
      - ls -a
      - npm run test-api -- --grep @skip --invert 
  post_build:
    commands:
      - aws s3 mv s3://rll-qa-report-stg/rll-stg-environment-bucket/api-event/mochawesome.html s3://rll-qa-report-stg/rll-stg-environment-bucket/api-event/mochawesome-$(date +\%d-\%m-\%Y-\%H:\%M).html
      - aws s3 mv s3://rll-qa-report-stg/rll-stg-environment-bucket/api-event/mochawesome.json s3://rll-qa-report-stg/rll-stg-environment-bucket/api-event/mochawesome-$(date +\%d-\%m-\%Y-\%H:\%M).json
      - ls -la 
      - ls -la reports/mochawesome
      - aws s3 cp $CODEBUILD_SRC_DIR/qa_test/reports/mochawesome/mochawesome.html s3://rll-qa-report-stg/rll-stg-environment-bucket/api-event/mochawesome.html --acl public-read
      - aws s3 cp $CODEBUILD_SRC_DIR/qa_test/reports/mochawesome/mochawesome.json s3://rll-qa-report-stg/rll-stg-environment-bucket/api-event/mochawesome.json --acl public-read
